import { HeadConfig } from "vitepress";
import packageJson from "../../packages/masc/package.json";

export default [
	["link", { rel: "icon", type: "image/svg+xml", href: "/logo.svg" }],
	["link", { rel: "icon", type: "image/png", href: "/logo.png" }],
	["link", { rel: "apple-touch-icon", href: "/logo.png" }],
	["meta", { name: "image", content: "/logo.png" }],
	["meta", { name: "viewport", content: "width=device-width, initial-scale=1.0" }],
	["meta", { name: "keywords", content: "masc, masc-vue, masc-vue-components, masc-vue-3, masc-vue-3-components, daisyui vue" }],
	["meta", { name: "author", content: "Mohammad Siddiqui" }],
	["meta", { name: "theme-color", content: "#7957d5" }],
	["meta", { name: "og:title", content: "MASC Vue 3 Components" }],
	["meta", { name: "og:description", content: "MASC Vue 3 Components based on daisyui and tailwindcss" }],
	["meta", { name: "og:image", content: "https://masc-vue.netlify.app/logo.png" }],
	["meta", { name: "og:url", content: "https://masc-vue.netlify.app" }],
	["meta", { name: "og:type", content: "website" }],
	["meta", { name: "og:locale", content: "en" }],
	["meta", { name: "og:site_name", content: "MASC Vue Components" }],
	["meta", { name: "twitter:card", content: "summary_large_image" }],
	["meta", { name: "twitter:creator", content: "@siddiqui_pro" }],
	["meta", { name: "twitter:title", content: "MASC Vue 3 Components" }],
	["meta", { name: "twitter:description", content: "MASC Vue 3 Components based on daisyui and tailwindcss" }],
	["meta", { name: "twitter:image", content: "https://masc-vue.netlify.app/logo.png" }],
	["meta", { name: "twitter:url", content: "https://masc-vue.netlify.app" }],
	["meta", { name: "twitter:label1", content: "Version" }],
	["meta", { name: "twitter:data1", content: packageJson.version }],
	["meta", { name: "twitter:label2", content: "License" }],
	["meta", { name: "twitter:data2", content: "MIT" }],
	["meta", { name: "twitter:label3", content: "Github" }],
	["meta", { name: "twitter:data3", content: "https://github.com/siddiquipro" }],
	["meta", { name: "twitter:label4", content: "NPM" }],
	["meta", { name: "twitter:data4", content: "https://www.npmjs.com/package/masc-vue" }],
] satisfies HeadConfig[];
